name: benchmarks

on: [push]

jobs:
  benchmark:
    name: Report benchmarks for Qi forms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Package and its Dependencies
        run: make install
      - name: Run benchmark
        run: make report-benchmarks
