name: docs

on:
  push:
    paths:
      - 'qi-doc/scribblings/**'
      - '.github/workflows/docs.yml'

defaults:
  run:
    shell: bash

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Build and deploy backup docs
    environment: test-env
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Package and its Dependencies
        run: make install
      - name: Build docs for hosting
        run: make build-packaged-docs
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: docs/qi
          branch: gh-pages
