name: docs

on:
  workflow_run:
    workflows: [build]
    types: [completed]

defaults:
  run:
    shell: bash

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Build and deploy backup docs
    environment: test-env
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Package and its Dependencies
        run: make install
      - name: Build docs
        run: make build-docs
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: qi-doc/doc
          branch: gh-pages
